### ISSUE TITLE
Strange behavior when calculating Layers (probably Aparapi related)

### ISSUE THREAD

**Issue by wandergibaut** [ivan-vasilev/neuralnetworks#50]
Hi!
First of all I have no experience with GPU processing and my personal computer don't even have one.
I'm using your package inside a Cognitive Architecture project and at some point its involve calculate some inputs in a loop. There I call a self-made method that uses some lines from the "propagateForward".

The method is:
`public void calculate(Matrix input){
        Set<Layer> calculatedLayers = new UniqueList<Layer>();
        calculatedLayers.add(mlp.getInputLayer());
	activations.addValues(mlp.getInputLayer(), input);
        mlp.getLayerCalculator().calculate(mlp, mlp.getOutputLayer(), calculatedLayers, activations);
    }`
And I call it with "TrainingInputProvider.getNextInput().getInput()" as parameter.

The problem is that after the first iteration (which seens to run without any issue) this "calculate" method thows a error:

Exception in thread "Thread-7" java.lang.UnsatisfiedLinkError: com.amd.aparapi.KernelRunner.runKernelJNI(JLcom/amd/aparapi/Range;ZI)I

and them the Thread is gone.

I feel that I'm doing something wrong as I think that it should OR work though all the loop OR not work at all.

Can you help me with this ?

**Comment by grfrost** [comment]
A few questions.

Are you able to run any of the sample Aparapi apps on this machine?

It is not clear from this whether your code is GPU ish ;) Specifically the
The code above is full of Java'isms that I would never expect to run on a
GPU.

At the core of your code I assume you have a 'kernel' which you expect to
run.   Can you set the mode to 'JTP' or even 'SEQ' to see if the code runs
on it's own. Sans GPU/OpenCL.

Do you know that OpenCL will run on this machine..

Gary



On Mon, Jun 19, 2017 at 6:26 PM, Wandemberg Gibaut <notifications@github.com

**Comment by wandergibaut** [comment]
In the Lab Computer I was able to run the Aparapi samples perfectly, but I didn't try on my PC.
And yes, the problem was on this setup on it. Otherwise, It runs ok without GPU.

Thanks for your help, Gary!

**Comment by wandergibaut** [comment]
In the Lab Computer I was able to run the Aparapi samples perfectly, but I didn't try on my PC.
And yes, the problem was on this setup on it. Otherwise, It runs ok without GPU.

Thanks for your help, Gary!
